package code.school.internship.classes_and_objects.homework.homework11;
/*
public class ArithmeticExceptionTest {
    public static void main(String[] args) {

        try{
            int i=10/0; //will throw ArithmeticException
        }catch(ArithmeticException){
            System.out.println("ArithmeticException handled in catch block");
        }
        finally{
            System.out.println("finally block executed");
        }

        System.out.println("code after try-catch-finally block");
    }
}

 */
